### ISSUE TITLE
需求,多账号启动延迟,运行结果推送

### ISSUE THREAD

**Issue by knva** [BenZinaDaze/wsdaily#1]
众所周知,角色过多可能导致卡房间等问题,加入账号启动延迟解决这个问题.

程序运行时一般都在服务器中,应将结果及时推送到用户端,
推送需求:
pushplus
serverchan
telegram
cqhttp
....
推送例子:javascript
https://github.com/shufflewzc/faker3/blob/main/sendNotify.js

**Comment by BenZinaDaze** [comment]
[Lasest](https://github.com/BenZinaDaze/wsdaily/releases/latest)
