### ISSUE TITLE
wsdaily_linux_arm64文件无法在手机上运行

### ISSUE THREAD

**Issue by xujiameng** [BenZinaDaze/wsdaily#6]
大佬你好，非常感谢你开发了挖矿传说日常工具，我在多台电脑上都备份有一份wsdaily。

目前在win和linux系统上使用都没有遇到任何问题。唯一有遗憾的是，我无法在我的红米手机（型号：k40, cpu：晓龙875）上使用Termux运行，每次执行都会出现这样的错误，这困扰了我很久。

[~]$ ./wsdaily --mode run
平台:linux_arm64,版本:v1.10
[更新出错 ERROR]2022/08/18 04:01:50 main.go:1073: Get "https://api.github.com/repos/BenZinaDaze/wsdaily/tags": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:46427->[::1]:53: read: connection refused
[读取配置]2022/08/18 04:01:50 读取配置成功
[定时任务]2022/08/18 04:01:50 开启所有日常任务
[获取WS连接 ERROR]2022/08/18 04:01:50 main.go:275: Get "http://www.wamud.com/game/getserver": dial tcp: lookup www.wamud.com on [::1]:53: read udp [::1]:43504->[::1]:53: read: connection refused

大佬能花时间解决一下么？我对Go语言还有网络相关知识不甚了解。拜托了！

**Comment by BenZinaDaze** [comment]
看描述貌似是dns的问题，试着在etc目录下创建resolv.conf文件，写入
`nameserver 8.8.8.8`
指定下dns

**Comment by xujiameng** [comment]
> 

嗯。。。有一个小问题，我的手机一直没有root，没法直接在etc下新建文件，有什么别的迂回的方法能在etc下新建文件么？我尝试用Termux cd 到etc但是没有找到路径。

**Comment by BenZinaDaze** [comment]
重新推了个版本，可以试一下

**Comment by xujiameng** [comment]
> 重新推了个版本，可以试一下

谢谢大佬，已经能够正常使用。爱你（づ￣3￣）づ╭❤～
